---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysq-bk-s3
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mysq-bk-s3
              image: d3ividdy/mysql-bk-s3:latest
              env:
              - name: MYSQLDUMP_OPTIONS
                value: ""
              - name: MYSQLDUMP_DATABASE
                value: ""
              - name: MYSQL_HOST
                value: ""
              - name: MYSQL_PORT
                value: ""
              - name: MYSQL_USER
                value: ""
              - name: MYSQL_PASS
                value: ""

              - name: S3_ACCESS_KEY_ID
                value: ""
              - name: S3_SECRET_ACCESS_KEY
                value: ""
              - name: S3_BUCKET
                value: ""
              - name: S3_PREFIX
                value: ""
              - name: S3_REGION
                value: ""