version: '3.7'
services:
  backup_data:
    #Dump Data Only
    container_name: backup_data
    image: d3ividdy/mysql-bk-s3:latest
    environment:
      MYSQLDUMP_OPTIONS: "--default-character-set=utf8 --single-transaction=TRUE --routines --events --no-create-info=TRUE"
      MYSQLDUMP_DATABASE: bulla_dfe
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root

      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      S3_BUCKET: ""
      S3_PREFIX: backup
      S3_REGION: "us-east-1"

  backup_struct:
    #Dump Struct Only
    container_name: backup_struct
    image: d3ividdy/mysql-bk-s3:latest
    environment:
      MYSQLDUMP_OPTIONS: "--default-character-set=utf8 --single-transaction=TRUE --no-data --skip-triggers"
      MYSQLDUMP_DATABASE: bulla_dfe
      MYSQL_HOST: "mysql-srv"
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root

      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      S3_BUCKET: ""
      S3_PREFIX: backup
      S3_REGION: "us-east-1"
